### ISSUE TITLE
Reserved Standardized Block Type Codes

### ISSUE THREAD

**Issue by bubbasnmp** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#166]
Are the "Reserved" ranges at end of the list accurate and can they be arranged in numerical order?  

```
0x0A0D0D0A	Section Header Block (Section 4.1)
0x0A0D0A00-0x0A0D0AFF	Reserved. Used to detect trace files corrupted because of file transfers using the HTTP protocol in text mode.
0x000A0D0A-0xFF0A0D0A	Reserved. Used to detect trace files corrupted because of file transfers using the HTTP protocol in text mode.
0x000A0D0D-0xFF0A0D0D	Reserved. Used to detect trace files corrupted because of file transfers using the HTTP protocol in text mode.
0x0D0D0A00-0x0D0D0AFF	Reserved. Used to detect trace files corrupted because of file transfers using the FTP protocol in text mode.
0x80000000-0xFFFFFFFF	Reserved for local use.
```

The ranges for the first two put SHB and `0x40000BAD` in reserved sections.  
```
0x000A0D0A-0xFF0A0D0A	Reserved. Used to detect trace files corrupted because of file transfers using the HTTP protocol in text mode.
0x000A0D0D-0xFF0A0D0D	Reserved. Used to detect trace files corrupted because of file transfers using the HTTP protocol in text mode.

0x0A0D0A00-0x0A0D0AFF	Reserved. Used to detect trace files corrupted because of file transfers using the HTTP protocol in text mode.

0x0A0D0D0A	Section Header Block (Section 4.1)

0x0D0D0A00-0x0D0D0AFF	Reserved. Used to detect trace files corrupted because of file transfers using the FTP protocol in text mode.

0x80000000-0xFFFFFFFF	Reserved for local use. (bit 31 is set to 1)
```
(Initially added here: https://github.com/IETF-OPSAWG-WG/draft-ietf-opsawg-pcap/blob/f7fdc15a7b511a82bcb788d1d9886568415fa5ea/draft-tuexen-opsawg-pcapng.xml#L1047  ) ???

**Comment by guyharris** [comment]
> The ranges for the first two put SHB and 0x40000BAD in reserved sections.

They were not *intended* to be ranges, they were intended to be sets of 256 values in which the uppermost 8 bits had values from 0x00 to 0xFF and the other bytes had specific values, but the use of a hyphen made inferring that they represented a range a reasonable thing to do.

In e1099094acb43ad7fe6e19290772cbb79dca6b5c I changed all of the non-range "ranges" of that sort (including the one that happens to be a range because the non-fixed bits are the lower 8 bits) to be single items with "?? in place of the 8 bits that can have a value from 0x00 to 0xFF.
