### ISSUE TITLE
Release the RFC into public domain

### ISSUE THREAD

**Issue by KOLANICH** [IETF-OPSAWG-WG/draft-ietf-opsawg-pcap#49]
Hello. I'm creating a derivative work based on the RFC (more precisely I have translated most of the spec (not quite fully, some features are missing because of limitations of present KS) into Kaitai Struct language, but I wanna insert there the comments copied from the RFC and modify some of them to fit better). As I understand, the copyrights on the RFC make it illegal to insert and modify the quotes from it. So I wonder if copyright holders could release this into public domain, so it to be legal to do the needed things.

**Comment by guyharris** [comment]
> As I understand, the copyrights on the RFC make it illegal to insert and modify the quotes from it.

The copyright notice says:

> This document is subject to BCP 78 and the IETF Trust's Legal Provisions Relating to IETF Documents (https://trustee.ietf.org/license-info) in effect on the date of publication of this document.

So are you referring to the "to copy, publish, display and distribute unmodified portions of IETF Contributions and IETF Documents and translations thereof" part of the "Licenses For Use Outside the IETF Standards Process." section of [version 5 of the Legal Provisions Relating to IETF Documents](https://trustee.ietf.org/documents/IETF-TLP-5_001.html), which allows stuff to be copied, but not modified?

The copyright is a bit strange because the document has not yet been made an Internet-Draft, so I'm not sure it's *really* copyright by the IETF Trust yet.

> So I wonder if copyright holders could release this into public domain

Not if we ever turn it into an Internet-Draft or an RFC, as I think the IETF Trust will insist on their legal provisions applying.

> so it to be legal to do the needed things.

I suspect you can figure out some other way to add the comments; "fit better" is different from "fit at all".  You may have to add additional framing information, but I think the KSL version will survive the process.

**Comment by q2dg** [comment]
Well...august is expiration time, so ...
